/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipo_practica_9;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author mamechapa
 */
public class Edicion extends javax.swing.JPanel {

    private Inicio panelAnterior;
    private Libro libro;
    /**
     * Creates new form Edicion
     */
    public Edicion(Inicio panelAnterior, Libro libro) {
        initComponents();
        this.panelAnterior = panelAnterior;
        this.libro = libro;
        
        jTextFieldNombre.setText(libro.getNombre());
        jTextFieldAutor.setText(libro.getAutor());
        jTextFieldGenero.setText(libro.getGenero());
        jTextFieldAnio.setText(libro.getAño());
        
                
        
        saveButton.addActionListener(new SaveListener(this));
    }
    
    public void guardarLibro(){
        libro.setNombre(jTextFieldNombre.getText());
        libro.setAutor(jTextFieldAutor.getText());
        libro.setGenero(jTextFieldGenero.getText());
        libro.setAño(jTextFieldAnio.getText());
        panelAnterior.guardarLibro(libro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jLabelAnio = new javax.swing.JLabel();
        jTextFieldAnio = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        jTextFieldNombre.setText("jTextField1");

        jLabelNombre.setText("Nombre");

        jLabelAutor.setText("Autor");

        jTextFieldAutor.setText("jTextField2");

        jLabelGenero.setText("Genero");

        jTextFieldGenero.setText("jTextField3");

        jLabelAnio.setText("Año");

        jTextFieldAnio.setText("jTextField4");

        saveButton.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldAutor)
                    .addComponent(jTextFieldGenero)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelAutor)
                            .addComponent(jLabelGenero)
                            .addComponent(jLabelAnio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldAnio))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(saveButton)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAnio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    class SaveListener implements ActionListener {
        Edicion panelEdicion;

        public SaveListener(Edicion panelEdicion) {
            this.panelEdicion = panelEdicion;
        }
        
        public void actionPerformed(ActionEvent e) {
            panelEdicion.guardarLibro();
            panelEdicion.setVisible(false);
            panelAnterior.setVisible(true);
        }
    }
}
