/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipo_practica_9;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author mamechapa
 */
public class Edicion extends JPanel {

    private JTextField nombreLibro;
    private JTextField autorLibro;
    private JTextField generoLibro;

    private JFrame frame;

    private Libro libro;

    /**
     * Creates new form Edicion
     */
    Edicion(JFrame frame, Libro libro) {
        initComponents();
        this.frame = frame;
        this.libro = libro;

        //Inicializacion jlabel
        JLabel nombre = new JLabel("Nombre");
        JLabel autor = new JLabel("Autor");
        JLabel genero = new JLabel("Genero");
        JLabel anio = new JLabel("Año");

        //Inicializacion textfield
        nombreLibro = new JTextField(libro.getNombre());
        autorLibro = new JTextField(libro.getAutor());
        generoLibro = new JTextField(libro.getGenero());
        JButton save = new JButton("Guardar");

        //Añadimos al panel
        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        add(nombre);
        add(nombreLibro);
        add(autor);
        add(autorLibro);
        add(genero);
        add(generoLibro);
        add(save);
        setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
