/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipo_practica_9;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author mamechapa
 */
public class Nuevo extends javax.swing.JPanel {

    private Inicio panelAnterior;
    private Libro libro;

    /**
     * Creates new form Edicion
     */
    public Nuevo(Inicio panelAnterior, Libro libro) {
        initComponents();
        this.panelAnterior = panelAnterior;
        this.libro = libro;

        jTextFieldNombre.setText("");
        jTextFieldAutor.setText("");
        jTextFieldGenero.setText("");
        jTextFieldAnio.setText("");

        saveButton.addActionListener(new SaveListener(this));
        volverButton.addActionListener(new VolverListener(this));
    }

    public void guardarLibro() {
        libro.setNombre(jTextFieldNombre.getText());
        libro.setAutor(jTextFieldAutor.getText());
        libro.setGenero(jTextFieldGenero.getText());
        libro.setAño(jTextFieldAnio.getText());
        panelAnterior.guardarLibro(libro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jLabelAnio = new javax.swing.JLabel();
        jTextFieldAnio = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();

        jTextFieldNombre.setText("jTextField1");

        jLabelNombre.setText("Nombre");

        jLabelAutor.setText("Autor");

        jTextFieldAutor.setText("jTextField2");

        jLabelGenero.setText("Genero");

        jTextFieldGenero.setText("jTextField3");

        jLabelAnio.setText("Año");

        jTextFieldAnio.setText("jTextField4");

        saveButton.setText("Guardar");

        volverButton.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldAutor)
                    .addComponent(jTextFieldGenero)
                    .addComponent(jTextFieldAnio)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelAutor)
                            .addComponent(jLabelGenero)
                            .addComponent(jLabelAnio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 248, Short.MAX_VALUE)
                        .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAnio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(volverButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables

    class SaveListener implements ActionListener {

        Nuevo panelEdicion;

        public SaveListener(Nuevo panelEdicion) {
            this.panelEdicion = panelEdicion;
        }

        public void actionPerformed(ActionEvent e) {
            panelEdicion.guardarLibro();
            panelEdicion.setVisible(false);
            panelAnterior.setVisible(true);
        }
    }

    class VolverListener implements ActionListener {

        Nuevo panelEdicion;

        public VolverListener(Nuevo panelEdicion) {
            this.panelEdicion = panelEdicion;
        }

        public void actionPerformed(ActionEvent e) {
            panelEdicion.setVisible(false);
            panelAnterior.setVisible(true);
        }
    }
}
